name: CI-CD

on:
  push:
    branches: [main]

jobs:
  backend:
    name: Test + Build backend
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install deps
        run: cd back && npm ci

      - name: Run tests
        run: cd back && npm test

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_USERNAME }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build + Push backend image
        uses: docker/build-push-action@v5
        with:
          context: ./back
          push: true
          tags: ghcr.io/${{ secrets.GHCR_USERNAME }}/mon-projet:back-latest

  frontend:
    name: Build frontend (if backend ok)
    runs-on: ubuntu-latest
    needs: backend

    steps:
      - uses: actions/checkout@v4

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_USERNAME }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build + Push frontend image
        uses: docker/build-push-action@v5
        with:
          context: ./front
          push: true
          tags: ghcr.io/${{ secrets.GHCR_USERNAME }}/mon-projet:front-latest
